name: location_test
description: Flutter Login and GPS Location Tracking

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  flutter:
    sdk: flutter
  get: ^4.6.6
  google_sign_in: ^6.1.5
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
