name: location_test
description: Flutter Login and GPS Location Tracking

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  get: ^4.6.6
  google_sign_in: ^6.1.5
  location: ^5.0.3
  location_platform_interface: ^3.1.2
  shared_preferences: ^2.2.1

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/imgs/
    - assets/svgs/
